directory: /Users/regis/Desktop/Music/beets
library: /Users/regis/Desktop/Music/musiclibrary.db
import:
  move: yes
plugins: lyrics fetchart
paths: 
  default: $albumartist/$album%aunique{} ($year)/$track $title
